# Generated by Django 6.0.5 on 2026-05-21 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('tagline', models.CharField(blank=True, max_length=240)),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='en', max_length=2)),
                ('problem', models.TextField(help_text='What pain point does this project solve?')),
                ('solution', models.TextField(help_text='In 2-3 sentences, how does the project solve it?')),
                ('differentiation', models.TextField(blank=True)),
                ('competitors', models.TextField(blank=True)),
                ('target_users', models.TextField(help_text='Who is this for?')),
                ('personas', models.JSONField(blank=True, default=list)),
                ('features', models.JSONField(blank=True, default=list)),
                ('nice_to_have', models.JSONField(blank=True, default=list)),
                ('out_of_scope', models.JSONField(blank=True, default=list)),
                ('business_model', models.TextField(blank=True)),
                ('success_metrics', models.TextField(blank=True)),
                ('stack', models.CharField(blank=True, max_length=240)),
                ('integrations', models.TextField(blank=True)),
                ('hosting', models.CharField(blank=True, max_length=120)),
                ('entities', models.JSONField(blank=True, default=list)),
                ('timeline', models.CharField(blank=True, max_length=120)),
                ('budget', models.CharField(blank=True, max_length=120)),
                ('risks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('business_plan', 'Business Plan'), ('specifications', 'Cahier des Charges'), ('user_stories', 'User Stories'), ('use_case_diagram', 'Use Case Diagram'), ('erd_diagram', 'Entity-Relationship Diagram'), ('flow_diagram', 'User Flow Diagram'), ('custom', 'Custom Document')], default='custom', max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('is_generated', models.BooleanField(default=False, help_text='True if this document was produced by the generators (vs hand-written).')),
                ('prompt', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='planner.project')),
            ],
            options={
                'ordering': ['kind', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anthropic_api_key', models.CharField(blank=True, help_text='Your Anthropic API key. Used to call Claude for document generation.', max_length=200)),
                ('default_language', models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='en', help_text='Default language for newly created projects.', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
