# Generated by Django 6.0.5 on 2026-05-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('tagline', models.CharField(blank=True, max_length=240)),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='en', help_text='Language of the generated documents.', max_length=2)),
                ('problem', models.TextField(help_text='What pain point does this project solve?')),
                ('solution', models.TextField(help_text='In 2-3 sentences, how does the project solve it?')),
                ('differentiation', models.TextField(blank=True, help_text='What makes it different from existing alternatives?')),
                ('competitors', models.TextField(blank=True, help_text='Comma-separated list of known competitors.')),
                ('target_users', models.TextField(help_text='Who is this for? Describe the main audience.')),
                ('personas', models.JSONField(blank=True, default=list, help_text='List of personas as {name, role, goal}. The interview form splits this from a textarea.')),
                ('features', models.JSONField(blank=True, default=list, help_text='Must-have features (one per line in the form).')),
                ('nice_to_have', models.JSONField(blank=True, default=list, help_text='Nice-to-have features (one per line in the form).')),
                ('out_of_scope', models.JSONField(blank=True, default=list, help_text='Explicitly excluded features (one per line in the form).')),
                ('business_model', models.TextField(blank=True, help_text="How does the project make money? (or 'open source')")),
                ('success_metrics', models.TextField(blank=True, help_text='What does success look like? Concrete KPIs.')),
                ('stack', models.CharField(blank=True, help_text='Preferred tech stack (e.g. Django + Postgres + React).', max_length=240)),
                ('integrations', models.TextField(blank=True, help_text='Comma-separated list of external services / APIs.')),
                ('hosting', models.CharField(blank=True, help_text='Where will it run? (e.g. AWS, Fly.io, on-prem)', max_length=120)),
                ('entities', models.JSONField(blank=True, default=list, help_text='Data model entities as {name, fields}. Used to draw the ERD.')),
                ('timeline', models.CharField(blank=True, help_text="Target delivery window (e.g. 'MVP in 6 weeks').", max_length=120)),
                ('budget', models.CharField(blank=True, help_text='Budget / team size.', max_length=120)),
                ('risks', models.TextField(blank=True, help_text='Known risks and dependencies.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
