# Generated by Django 6.0.5 on 2026-05-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0002_project_is_draft_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="phase",
            field=models.CharField(
                choices=[("intake", "Intake"), ("assistant", "Assistant")],
                default="intake",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="proposal_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("applied", "Applied"),
                    ("discarded", "Discarded"),
                ],
                default="",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="proposals",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
