# Generated by Django 6.0.5 on 2026-05-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0003_chatmessage_phase_chatmessage_proposal_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="proposal_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "None"),
                    ("pending", "Pending"),
                    ("applied", "Applied"),
                    ("discarded", "Discarded"),
                ],
                default="",
                max_length=12,
            ),
        ),
    ]
