# Generated by Django 6.0.5 on 2026-05-22 07:05

from django.db import migrations, models

# Mirror of Document._KIND_CATEGORY (kept local so the migration is stable even
# if the model map changes later).
_KIND_CATEGORY = {
    "business_plan": "business",
    "specifications": "system_design",
    "user_stories": "app_design",
    "use_case_diagram": "system_design",
    "erd_diagram": "data_design",
    "flow_diagram": "app_design",
}


def backfill_categories(apps, schema_editor):
    Document = apps.get_model("planner", "Document")
    for kind, category in _KIND_CATEGORY.items():
        Document.objects.filter(kind=kind).update(category=category)
    # custom docs keep the "other" default


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0005_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="category",
            field=models.CharField(
                choices=[
                    ("business", "Business"),
                    ("system_design", "System Design"),
                    ("system_modeling", "System Modeling"),
                    ("data_design", "Data Design"),
                    ("app_design", "App Design"),
                    ("other", "Other"),
                ],
                default="other",
                help_text="Coarse grouping on the project page. Auto-set from kind for built-in documents; editable for custom ones.",
                max_length=20,
            ),
        ),
        migrations.RunPython(backfill_categories, migrations.RunPython.noop),
    ]
