# Generated by Django 6.0.5 on 2026-05-22 09:51

import django.db.models.deletion
from django.db import migrations, models


def backfill_conversations(apps, schema_editor):
    """Move existing assistant messages into a 'General' conversation per project."""

    Conversation = apps.get_model("planner", "Conversation")
    ChatMessage = apps.get_model("planner", "ChatMessage")

    project_ids = (
        ChatMessage.objects.filter(phase="assistant")
        .values_list("project_id", flat=True)
        .distinct()
    )
    for project_id in project_ids:
        conv = Conversation.objects.create(project_id=project_id, title="General")
        ChatMessage.objects.filter(
            project_id=project_id, phase="assistant"
        ).update(conversation=conv)


def unbackfill(apps, schema_editor):
    ChatMessage = apps.get_model("planner", "ChatMessage")
    ChatMessage.objects.filter(phase="assistant").update(conversation=None)


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0006_document_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="New conversation", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="planner.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="planner.conversation",
            ),
        ),
        migrations.RunPython(backfill_conversations, unbackfill),
    ]
