# Generated by Django 6.0.5 on 2026-05-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0007_conversation_chatmessage_conversation"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="chatmessage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("conversation__isnull", False), ("phase", "assistant")),
                    models.Q(("conversation__isnull", True), ("phase", "intake")),
                    _connector="OR",
                ),
                name="chatmessage_phase_conversation_consistency",
            ),
        ),
    ]
