# Generated by Django 6.0.5 on 2026-05-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0008_chatmessage_chatmessage_phase_conversation_consistency"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="model",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="conversation",
            name="provider",
            field=models.CharField(
                choices=[
                    ("claude", "Claude"),
                    ("oss", "Local / OSS (Ollama-compatible)"),
                ],
                default="claude",
                max_length=10,
            ),
        ),
    ]
