# Generated by Django 6.0.5 on 2026-05-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0009_conversation_model_conversation_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="ai_provider",
            field=models.CharField(
                choices=[
                    ("claude", "Claude"),
                    ("oss", "Local / OSS (Ollama-compatible)"),
                ],
                default="claude",
                help_text="Preferred backend for generating documents.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="oss_model",
            field=models.CharField(
                blank=True,
                help_text="Local/OSS model id used when generating with the local provider (e.g. gemma4:26b). Blank uses the server's OSS_MODEL default.",
                max_length=100,
            ),
        ),
    ]
